image: centos:6
types:
- build
build_rpm:
  type: build
  script:
  - yum install -y epel-release
  - yum install -y golang make git gzip rpm-build nc
  - make docker
  - rsync -aP /build/RPMS/x86_64/*.rpm rsync://repo6.itv.restr.im/infra/6/x86_64/
  - echo 'infra/6/x86_64' | nc -w5 repo6.itv.restr.im 8008
  artifacts:
    paths:
    - /build/RPMS/x86_64/*.rpm
  tags:
  - docker
  only:
  - tags
